### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by harmdhast** [googleben/ArmaCOM#3]
Hello,
any plans for supporting linux ?

**Comment by Roqarr** [comment]
My understanding is that the pass-through is not supported on Linux. Many features are not able to be successfully implemented in mods, such as acre and tear, as well as other USB input devices like trackir.

**Comment by googleben** [comment]
Serial communications should be implementable in Linux, but it would take a rewrite of the current system as it's written directly using the Windows API. The TCP support is built with Boost though, which should work cross-OS no problem. So for right now I'm not planning on compiling Linux binaries, especially since I don't have an easy way to test them due to how Linux vs Windows dynamically linked libraries are implemented, but the TCP portion of the extension should compile and run on Linux just fine. In the near future I also plan on testing out Boost's serial comms library as a replacement, which I believe should also be cross platform - it's hard to say with serial though.

So short answer I don't plan on officially supporting Linux in the short term, but if you rip out the serial portion of the code, you should be able to compile it yourself. I'll probably explore compiling unsupported binaries for Linux, but that's pretty far down my pipeline for this extension at the moment.

**Comment by FatLurch** [comment]
This was my understanding as well.

However, I just looked up the extension documentation online: apparently as of version 1.69 ARMA can utilize Shared Objects with Linux.

This may be limited to servers only though, given the context on the page.

**Comment by harmdhast** [comment]
Thanks for the answer. I'll follow the project closely.
